site_name: Kya Saabzi Docs
site_description: "Functional and Use Case documentation for the Kya Saabzi App"
site_url: https://manav-gkmit.github.io/kya-saabzi-docs/
repo_name: Kya Saabzi
repo_url: https://github.com/manav-gkmit/kya-saabzi-docs

theme:
  name: material
  icon: 
    logo: material/food-apple
    repo: simple/github
  favicon: assets/ingredient.ico
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/lightbulb-off
        name: Switch to system preference
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.blocks.caption


nav:
  - Home: index.md
  - Use Cases:
    - Functional: use-cases/functional.md
  - Architecture:
    - AWS Specific: architecture/aws.md
    - Data Modeling: architecture/data-model.md
    - Data Flow: architecture/data-flow.md
    - Database Indices: architecture/indexing.md
    - Security: architecture/auth.md
  - Setup:
    - Environment: setup/environment.md